name: CI - Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 493608842618.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t mediplus:v1 .
          docker tag mediplus:v1 493608842618.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
          docker push 493608842618.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1


  deploy:
     runs-on: ubuntu-latest
     needs: build-push
     steps:
       - name: Check SSH key
         run: |
           echo "${{ secrets.SSH_KEY }}" > mykey.pem
           chmod 600 mykey.pem
           cat mykey.pem

           ssh -o   StrictHostKeyChecking=no -i mykey.pem ubuntu@54.173.72.91 "docker ps"
            
            ssh -o   StrictHostKeyChecking=no -i mykey.pem ubuntu@54.173.72.91 "hostnamectl"